Repository WatchItTeam/WatchIt, pull requests merged in 2018-05, with the labels that each got.

#97 Better fallbacks when no image
  src/components/DetailsBanner.js
  src/components/DetailsTitle.js
  src/components/ImageWithFallback.js
  src/components/PosterCard.js
  src/components/PosterGrid.js
  src/containers/MovieInformationContainer.js
  src/css/DetailsBanner.scss
  src/css/ImageWithFallback.scss
  src/css/PosterCard.scss
Labels: enhancement

#96 Bugfix detailsinfo
  src/containers/MovieInformationContainer.js
Labels: bug

#99 Implement browse year for both movies and shows
  src/api/APIUtils.js
  src/components/BrowsePage.js
  src/components/BrowseYear.js
  src/containers/BrowseMoviesContainer.js
  src/containers/BrowseTvContainer.js
  src/containers/HomepageContainer.js
  src/css/BrowseYear.scss
  src/css/ErrorMessage.scss
  src/css/Tabs.scss
  src/utils/createDebouncedFunc.js
Labels: enhancement

#101 Fix a bug where the poster wouldn't go over the banner
  src/css/DetailsTitle.scss
Labels: bug

#113 Delete movie
  src/Firebase/lists.js
  src/containers/UserList.js
Labels: Requirement

#114 Make drag and drop work
  src/Firebase/lists.js
  src/components/PosterCard.js
  src/components/PosterCardDropTarget.js
  src/components/PosterGrid.js
  src/components/Sidebar.js
  src/containers/MovieInformationContainer.js
  src/utils/toast.js
Labels: Requirement

#115 Make the detailspage more nice
  src/components/DetailsPage.js
  src/components/MovieInformationContainer.js
  src/components/Scroll.js
  src/components/Trailers.js
  src/containers/MovieInformationContainer.js
Labels: enhancement

#124 Fixdeletebug
  src/components/WatchList/ResponsiveList.js
  src/containers/UserList.js
Labels: Requirement, bug

#126 Update list title-bar
  src/components/WatchList/ResponsiveList.js
  src/css/CardList.scss
  src/css/ResponsiveList.scss
  src/css/responsive.scss
Labels: Suggestion, enhancement

#142 Animated scroll in Scroll component
  src/components/Scroll.js
  src/css/MovieInfo.scss
  src/css/Scroll.scss
  src/utils/smoothScroll.js
Labels: Suggestion

#149 Firebase episodes
  src/Firebase/UserContext.js
  src/Firebase/lists.js
  src/api/APIUtils.js
  src/components/DetailsTitle.js
  src/components/Episodes/EpisodeItem.js
  src/components/Episodes/EpisodeMobileItem.js
  src/components/Episodes/EpisodePage.js
  src/components/Episodes/Season.js
  src/components/SecondaryButton.js
  src/components/Tabs.js
  src/containers/App.js
  src/containers/EpisodeContainer.js
  src/css/EpisodeMobileItem.scss
  src/css/Season.scss
  src/css/Tabs.scss
Labels: enhancement
