Repository WatchItTeam/WatchIt, pull requests merged in 2018-04, with the labels that each got.

#2 ✅ Add a test component
  src/components/test.js
Labels: enhancement

#3 Add startup code
  .babelrc
  .eslintrc.js
  .gitignore
  README.md
  package-lock.json
  package.json
  public/index.html
  src/components/ScrollToTop.js
  src/containers/App.js
  src/index.js
  webpack.config.js
Labels: enhancement

#21 Add global styles
  package-lock.json
  package.json
  public/index.html
  src/css/_global.scss
  src/css/index.scss
  src/index.js
Labels: enhancement

#20 Add PosterCard and PosterGrid
  src/api/APIUtils.js
  src/components/PosterCard.js
  src/components/PosterGrid.js
  src/css/PosterCard.scss
  src/css/PosterGrid.scss
Labels: enhancement

#18 Removing the test component
  src/components/test.js
Labels: enhancement

#23 Add files to include an API key in our project
  .gitignore
  README.md
  src/api/APIkey.js
Labels: Requirement

#29 Add font-weights to homepage titles
  src/css/Homepage.scss
Labels: bug, enhancement

#30 Fix the API key so it is ignored for sure
  .gitignore
  README.md
  src/api/APIkeyPlaceholder.js
Labels: bug

#31 Postercard suggestion
  .gitignore
  src/api/APIkey.js
  src/css/PosterCard.scss
Labels: Suggestion

#35 Api crash fix and error handling
  src/api/APIUtils.js
  src/components/ErrorMessage.js
  src/components/PosterGrid.js
  src/containers/HomepageContainer.js
  src/css/ErrorMessage.scss
Labels: bug, enhancement

#51 Add polyfills for fetch and URLSearchParams
  package-lock.json
  package.json
  src/index.js
  webpack.config.js
Labels: enhancement

#47 Webpack updates
  package-lock.json
  package.json
  public/index.html
  public/manifest.json
  webpack.config.js
Labels: Suggestion

#58 Fix iOS style issues
  src/css/App.scss
  src/css/index.scss
Labels: enhancement

#59 Fix bug in Searchpage
  src/components/Searchpage.js
  src/containers/SearchpageContainer.js
Labels: enhancement

#55 Update start script to open localhost instead of 0.0.0.0
  package.json
Labels: Suggestion

#61 Add dynamic dark header
  src/containers/App.js
  src/containers/DynamicHeader.js
  src/css/Header.scss
  src/css/Searchbar.scss
Labels: enhancement

#82 Browse movies page
  src/api/APIUtils.js
  src/components/BrowseGenrePage.js
  src/components/BrowseMoviesPage.js
  src/components/Tabs.js
  src/components/TitleGrid.js
  src/containers/App.js
  src/containers/BrowseGenresContainer.js
  src/containers/BrowseMoviesContainer.js
  src/css/Tabs.scss
  src/css/TitleGrid.scss
  src/css/index.scss
  src/css/responsive.scss
Labels: Requirement
